### ISSUE TITLE
Since updating from 4.x to latest cannot deploy to a node.js script target

### ISSUE THREAD

**Issue by whydoidoit** [mkloubert/vs-deploy#29]
I get the error args.context.isCancelling is not a function.

**Comment by whydoidoit** [comment]
I notice that's in my deployment script, I guess the parameters being passed have changed.  Fixed it in my code.

**Comment by mkloubert** [comment]
@whydoidoit  Oh, sorry! I forget to notice that in [CHANGELOG.md](https://github.com/mkloubert/vs-deploy/blob/master/CHANGELOG.md) file.

Thank you very much for the hint! 👍 

For all who have the same (or a similar) problem:

According to the issue ["Click here to cancel" is not working](https://github.com/mkloubert/vs-deploy/issues/22#issuecomment-273177378), I improved and fixed the concept of cancelling deployments.

Cancellation now works event based. This is the reason why `isCancelling()` method does not exist in [DeployContext](https://mkloubert.github.io/vs-deploy/interfaces/_contracts_.deploycontext.html) interface anymore.

An example for a "replacement" is, that you define a variable inside the promise at the beginning, that stores if cancellation has been requested and is changed when event is raised, as you can see here[https://github.com/mkloubert/vs-deploy/wiki/target_script#implement-own-scripts]: 

```javascript

    return new Promise(function(resolve, reject) {
        var hasCancelled = false;

        args.context.once('deploy.cancel', function() {
            hasCancelled = true;
        });

        // now, your deployment code...
    });

```

**Comment by mkloubert** [comment]
**I readded the method since version 5.9.0.**

```javascript
    return new Promise(function(resolve, reject) {
        // ...

        if (args.context.isCancelling()) {
            // cancellation requested
        }

        // ...
    });
```

This makes it much easier, I think.
